### ISSUE TITLE
Not working on Alacritty.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [3rd/image.nvim#109]
Hi, the minimal working example gives me the following on Alacritty:
![image](https://github.com/3rd/image.nvim/assets/133555950/519027b6-448b-4a86-a194-b0e7c3431843)
I tested it on kitty and it worked as expected, but not on alacritty.
Thanks

**Comment by 3rd** [comment]
Hey, for Alacritty you need to setup ueberzugpp and configure it as the backend.

**Comment by aabbccddeeffggj** [comment]
> Hey, for Alacritty you need to setup ueberzugpp and configure it as the backend.

I see, I was kind of dumb. I indeed had changed the configuration for ueberzug in my neovim configuration, but forgot to do the same in the minimal working example.

Thanks anyway, great plugin!
