### ISSUE TITLE
Causes kitty to crash when changing window size

### ISSUE THREAD

**Issue by donovanglover** [3rd/image.nvim#11]
Not sure how to get meaningful logs but I'm able to reproduce a crash after scrolling up/down and toggling fullscreen in succession.

kitty: 0.29.0
neovim: v0.9.1
image.nvim: https://github.com/3rd/image.nvim/commit/24c312191ca6bc04e45610a7bcb984d3bf208820

**Comment by 3rd** [comment]
@kovidgoyal thanks for joining, but most importantly thanks for Kitty, it's the software I spend most of my time with, absolutely love it! (userland)
I noticed some weird rendering artifacts as well after upgrading Kitty, last week one instance got into an interesting state where rendering any image would make the whole background become transparent, and clearing the images would bring it back to normal.

**Comment by kovidgoyal** [comment]
You are welcome! And as always I am always happy to investigate bugs if you can provide reproducers. An easy way to do so is to use --dump-bytes when running kitty and perform the minimum steps needed to reproduce Then along with the terminal window size the dump should allow me to repro.
