### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by dacid44** [3rd/image.nvim#115]
Is image.nvim intended to work on windows, and if not, is there a possibility that might happen? There are a couple of terminal emulators for windows which should support the kitty image protocol (wezterm off the top of my head), so it seems feasible, but I'm getting this error, which looks like it might be related to OS support:

```
Failed to run `config` for image.nvim

...Local/nvim-data/lazy/image.nvim/lua/image/utils/term.lua:34: cannot resolve symbol 'ioctl': The specified procedure could not be found.^M


# stacktrace:
  - image.nvim\lua\image\utils\term.lua:34 _in_ **update_size**
  - image.nvim\lua\image\utils\term.lua:46
  - image.nvim\lua\image\utils\init.lua:7
  - image.nvim\lua\image\renderer.lua:2
  - image.nvim\lua\image\image.lua:2
  - image.nvim\lua\image\init.lua:1
  - ~\AppData\Local\nvim/lua/config/lazy.lua:9
  - ~\AppData\Local\nvim\init.lua:2
```

Or are there just some options I'm missing?

**Comment by dacid44** [comment]
Is there an alternative you can refer me to? I'm trying to get `molten-nvim` working (for viewing image output of jupyter notebooks). If not, that's understandable, but I'm just curious if you know of one.

**Comment by 3rd** [comment]
Not aware of any alternative :(
It's crashing when trying to get the terminal size, maybe if we find a workaround for that it could work on Win + Wez.
I think the other stuff should be compatible in theory...

**Comment by 3rd** [comment]
Hey, Wezterm is not "officially" supported because of the performance issues with rendering (when doing multi clear/draw sequences), but I can check if it got better. If it has decent performance now, and if we can read terminal info like cell size then it should work.
I wouldn't mind adjusting some things to work on Windows, but I wouldn't maintain it.

**Comment by GitMurf** [comment]
> I wouldn't mind adjusting some things to work on Windows, but I wouldn't maintain it.

Thanks for the quick response and the kind offer! I am not a terminal expert but would be happy to help maintain it after the first working iteration if that is something that would help :)

**Comment by GitMurf** [comment]
@3rd an update from the windows side. Windows Terminal just released sixel support! I was only really using wezterm previously for the image capabilities so now that Windows supports sized image rendering I’m curious if you think that is a quicker/better path for windows support in your plugin as opposed to the discussion above about wezterm?

https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-22-release/#sixel-image-support0

**Comment by 3rd** [comment]
That's great, I'd like to support sixel rendering somehow, I'm worried about how hard it would be to render images at arbitrary positions, but investigating. Anyway, glad Windows Terminal got cooler!

**Comment by GitMurf** [comment]
@3rd curious if you have made any progress on the sixel consideration to support windows users? Fyi, folke said his snacks images will not be supporting sixel so this could be a differentiator for image.nvim plugin :)
