### ISSUE TITLE
image rendered in md

### ISSUE THREAD

**Issue by niksingh710** [3rd/image.nvim#12]
os: Arch linux
terminal: foot
backend: ueberzug

with minimal config
![image](https://github.com/3rd/image.nvim/assets/60490474/c2afbdb7-5392-4231-9bda-dd71a2413f38)

with my config 
![image](https://github.com/3rd/image.nvim/assets/60490474/f4211294-0412-42f2-98db-f20d3cf339fc)

with minimal config the place holder comes but no image is previewed

below is my config
```lua
-- Example for configuring Neovim to load user-installed installed Lua rocks:
package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?/init.lua;"
package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?.lua;"
local istatus, image = pcall(require, "image")
if not istatus then
  return
end
image.setup({
  backend = "ueberzug",
  integrations = {
    markdown = {
      enabled = true,
      sizing_strategy = "auto",
      download_remote_images = true,
      clear_in_insert_mode = false,
    },
    neorg = {
      enabled = true,
      download_remote_images = true,
      clear_in_insert_mode = false,
    },
  },
  max_width = nil,
  max_height = nil,
  max_width_window_percentage = nil,
  max_height_window_percentage = 50,
  kitty_method = "normal",
  kitty_tmux_write_delay = 10,         -- makes rendering more reliable with Kitty+Tmux
  window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
  window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
})```

`luarocks --local --lua-version=5.1 install magick` used this command to install magick
and have `ueberzugpp` from aur
and imagemagick from arch repos

**Comment by 3rd** [comment]
Hey, just tried with the ueberzugpp's master and it seems ok, can you confirm that ueberzugpp works?

**Comment by niksingh710** [comment]
> Hey, just tried with the ueberzugpp's master and it seems ok, can you confirm that ueberzugpp works?

i can confirm that ueberzugpp works as i use that for preview script in fzf.
but i don't think that i am using  the master branch one i have the one from aur.

**Comment by niksingh710** [comment]
calling it via the fn mentioned in the readme video seems to work
`lua require("image").from_file("/home/niksingh710/.wallpapers/img.png"):render()`

if i store it on a local variable and then try to call render then it fails to find the local variable

**Comment by 3rd** [comment]
This is super weird, no idea what's going on.
Does it work with the Kitty backend?

**Comment by niksingh710** [comment]
> This is super weird, no idea what's going on. Does it work with the Kitty backend?

haven't tested will report after testing this.

**Comment by niksingh710** [comment]
with a minimal config it works on kitty with both backend `ueberzug` and `kitty`
but not on my config.
and if i use `foot` terminal with `ueberzug` on minimal config the placeholder comes and takes place but no image is shown.

**Comment by niksingh710** [comment]
okay so i got this working.
The issue is that i use vimwiki that makes my nvim detect any `.md` file as vimwiki and `image.nvim` fails to work there.

**Comment by 3rd** [comment]
Ah got it, it changes the filetype!
I'll change the way integrations work to add support for extending the allowed filetypes, meanwhile you can replace "markdown" with vimwiki's ft in here: https://github.com/3rd/image.nvim/blob/master/lua/image/integrations/markdown.lua

**Comment by niksingh710** [comment]
> Ah got it, it changes the filetype! I'll change the way integrations work to add support for extending the allowed filetypes, meanwhile you can replace "markdown" with vimwiki's ft in here: [`master`/lua/image/integrations/markdown.lua](https://github.com/3rd/image.nvim/blob/master/lua/image/integrations/markdown.lua?rgh-link-date=2023-08-20T10%3A50%3A41Z)

rn the workaround m using is explicitly setting the file type 

but will be looking forward for the changes.

i have an feature request don't know if it's in the scope of the project or not but if user selects a image in nvimtree or any file viewer image.nvim previews the image in buffer?
