### ISSUE TITLE
YALRMI: Yet Another LuaRocks Magick Issue

### ISSUE THREAD

**Issue by ArjunSahlot** [3rd/image.nvim#121]
I'm running an impractical setup for `image.nvim`, consisting of `Ubuntu 22.04`, `Wezterm`, and `tmux`. I believe I have everything installed properly yet it's still not working. I'm running into the infamous `image.nvim: magick rock not found, please install it and restart your editor` error.

Config details:
```bash
$ wezterm --version
wezterm 20240127-113634-bbcac864

$ tmux -V
tmux 3.2a

$ ls ~/.luarocks/share/lua/5.1/magick/
base_image.lua  enum.lua  gmwand  gmwand.lua  init.lua  thumb.lua  version.lua  wand  wand.lua

$ magick --version
Version: ImageMagick 7.1.1-27 Q16-HDRI x86_64 21931 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): fontconfig freetype jbig jng jpeg lzma pangocairo png tiff x xml zlib
Compiler: gcc (11.4)

$ luarocks --version
/usr/bin/luarocks 3.8.0
LuaRocks main command-line interface

$ luarocks --local install magick
Installing https://luarocks.org/magick-1.6.0-1.src.rock

magick 1.6.0-1 depends on lua 5.1 (5.1-1 provided by VM)
magick 1.6.0-1 is now installed in /home/arjun/.luarocks (license: MIT)

$ nvim -V1 -v
NVIM v0.10.0-dev-2201+g226466a46
Build type: RelWithDebInfo
LuaJIT 2.1.1706185428
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/home/arjun/apps/neovim/.deps/usr/include/luajit-2.1 -I/home/arjun/apps/neovim/.deps/usr/include -I/home/arjun/apps/neovim/build/src/nvim/auto -I/home/arjun/apps/neovim/build/include -I/home/arjun/apps/neovim/build/cmake.config -I/home/arjun/apps/neovim/src -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

$ ueberzug --version
ueberzugpp 2.9.2
```

I've also added the `set -gq allow-passthrough on` line in my tmux config, if that's relevant.

If you need my neovim config I've linked it [here](https://github.com/ArjunSahlot/.dotfiles/tree/main/.config/nvim) because it's too much to paste.

Is `image.nvim` even possible for `Wezterm`?

**Comment by ArjunSahlot** [comment]
After a bit more testing, I got it to work outside of tmux using the minimal config. When I used the minimal config inside of tmux, it said:
```
Failed to run `config` for image.nvim

...al/share/nvim/lazy/image.nvim/lua/image/utils/logger.lua:54: 16:42:06.006440 [image.nvim] tmux does not have allow-passthrough enabled

# stacktrace:
  - /image.nvim/lua/image/utils/logger.lua:54 _in_ **throw**
  - /image.nvim/lua/image/backends/kitty/init.lua:29 _in_ **setup**
  - /image.nvim/lua/image/init.lua:62 _in_ **setup**
```
... even though I had `set -gq allow-passthrough on` and reloaded(+restarted) my tmux config.

**Comment by 3rd** [comment]
We check that passthrough is on with `tmux show -Apv allow-passthrough`, try running that inside tmux, it should output "on".

**Comment by ArjunSahlot** [comment]
For me, this command did not work in `tmux 3.2a`. Once I updated to `tmux 3.3a` it started working. It might be worthwhile to put the working tmux versions in the README.

Regarding my situation now, minimal config works in tmux, but `image.nvim` still gives the same old `image.nvim: magick rock not found, please install it and restart your editor` error with my custom config. Are there any known conflicting plugins/setups? Why is there a `magick rock` installation problem on my config but no installation problem in the minimal one?

My neovim configuration is linked [here](https://github.com/ArjunSahlot/.dotfiles/tree/main/.config/nvim?rgh-link-date=2024-02-04T00%3A31%3A51Z) but I know it might be tedious for you to look through it. If you could just point me in the general direction of where I should look for bugs that'd be great. Thanks!

**Comment by ArjunSahlot** [comment]
Good news! I got it to work! For some reason the only way it would work is if I added `event = "VeryLazy"` to it. What I think was happening is initially at startup `image.nvim` wasn't able to find `magick rock` (don't know why) and then it just disabled itself. Instead, with `VeryLazy` on, it was able to find `magick rock` when it needed to, and worked.

Please let me know if my understanding is accurate! Thanks for this amazing plugin!

**Comment by 3rd** [comment]
Glad it worked! Yeah, I think there's some weird stuff going on with lazy.nvim.
Yesterday I upgraded my Neovim and started to get the rock error as well, and traced it to lazy. For some reason, if lazy was loaded the rock couldn't be resolved anymore, but when I removed it there were no issues.
I reverted back to the Neovim version I had before, and there's no issue with that one, so something must've changed in Neovim that makes lazy break rocks.
Rocks should be available long before lazy does its thing  :shrug:

**Comment by nfjdu** [comment]
Having the same problem. Im not using `lazy.nvim`. And Im not using tmux. 
```
[user@fedora ~]$ ls ~/.luarocks/share/lua/5.1/magick/
[base_image.lua  enum.lua  gmwand  gmwand.lua  init.lua  thumb.lua  version.lua  wand  wand.lua

[user@fedora ~]$ magick --version
[Version: ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (13.2)

[user@fedora ~]$ luarocks --version
[/usr/local/bin/luarocks 3.9.2
LuaRocks main command-line interface

[user@fedora ~]$ luarocks --local --lua-version=5.1 install magick
[Installing https://luarocks.org/magick-1.6.0-1.src.rock

magick 1.6.0-1 depends on lua 5.1 (5.1-1 provided by VM)
magick 1.6.0-1 is now installed in /home/user/.luarocks (license: MIT)

[user@fedora ~]$ nvim -V1 -v
[NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

Also, I added these lines at the start of my `/home/user/.config/nvim/init.lua`:
```
package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?/init.lua;"
package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?.lua;"
```

What can be a problem here?

**Comment by nfjdu** [comment]
> Having the same problem. Im not using `lazy.nvim`. And Im not using `tmux`.
> 
> ```
> [user@fedora ~]$ ls ~/.luarocks/share/lua/5.1/magick/
> [base_image.lua  enum.lua  gmwand  gmwand.lua  init.lua  thumb.lua  version.lua  wand  wand.lua
> 
> [user@fedora ~]$ magick --version
> [Version: ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI Modules OpenMP(4.5) 
> Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib zstd
> Compiler: gcc (13.2)
> 
> [user@fedora ~]$ luarocks --version
> [/usr/local/bin/luarocks 3.9.2
> LuaRocks main command-line interface
> 
> [user@fedora ~]$ luarocks --local --lua-version=5.1 install magick
> [Installing https://luarocks.org/magick-1.6.0-1.src.rock
> 
> magick 1.6.0-1 depends on lua 5.1 (5.1-1 provided by VM)
> magick 1.6.0-1 is now installed in /home/user/.luarocks (license: MIT)
> 
> [user@fedora ~]$ nvim -V1 -v
> [NVIM v0.9.5
> Build type: Release
> LuaJIT 2.1.1692716794
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```
> 
> Also, I added these lines at the start of my `/home/user/.config/nvim/init.lua`:
> 
> ```
> package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?/init.lua;"
> package.path = package.path .. ";" .. vim.fn.expand("$HOME") .. "/.luarocks/share/lua/5.1/?.lua;"
> ```
> 
> What can be a problem here? Thanks for help

Ok. I found a solution) 
`sudo dnf install ImageMagick-devel`
