### ISSUE TITLE
The picture cannot be displayed and the corresponding position is garbled.

### ISSUE THREAD

**Issue by Parsifa1** [3rd/image.nvim#122]
It looks like this::

![image](https://github.com/3rd/image.nvim/assets/31800073/b5c69e8d-2564-48a8-b64e-66b1cae1a467)

there is no error

**Comment by 3rd** [comment]
Hey, not sure what's going on, haven't seen it or heard of anyone having this before.

![image](https://github.com/3rd/image.nvim/assets/59587503/cde1aa33-9339-420e-9370-63b3d2d00ec1)

**Comment by 3rd** [comment]
Try upgrading everything :shrug:

**Comment by Parsifa1** [comment]
ok, i will try, thank you🥰
