### ISSUE TITLE
GIF rendered incorrectly

### ISSUE THREAD

**Issue by raffaem** [3rd/image.nvim#125]
It looks like GIFs are wrongly rendered.

Here is how [this gif](https://github.com/raffaem/waybar-mediaplayer/blob/master/showcase/progress_bar.gif) is rendered:

![image](https://github.com/3rd/image.nvim/assets/54762742/e758829e-1e5f-4bca-a34b-79e0a547c231)

While it should be:

![correct](https://raw.githubusercontent.com/raffaem/waybar-mediaplayer/master/showcase/progress_bar.gif)

**Comment by 3rd** [comment]
We don't have animation support, images are converted to PNGs.
There is animation support in Kitty, but it's out of scope for now: https://sw.kovidgoyal.net/kitty/graphics-protocol/#animation

**Comment by raffaem** [comment]
> We don't have animation support, images are converted to PNGs. There is animation support in Kitty, but it's out of scope for now: https://sw.kovidgoyal.net/kitty/graphics-protocol/#animation

But even then they are incorrectly converted.

The image, while static, is messed up and doesn't resemble any frame of the original animation.

**Comment by 3rd** [comment]
It's the frame magick outputs, we don't have control over that now :|
