### ISSUE TITLE
Install magick with home-manager  

### ISSUE THREAD

**Issue by wuliuqii** [3rd/image.nvim#13]
For NixOS user using home-manager, magick can be installed in extraLuaPackages as follows. I think this is much simpler.

```lua
programs.neovim = {
  enable = true;
  package = pkgs.neovim-nightly;
  extraLuaPackages = ps: [
    ps.magick
  ];
};
```

**Comment by 3rd** [comment]
Hey @wuliuqii, thanks for the contribution, I updated the README and switched to this myself!
