### ISSUE TITLE
JPEG Header detection supports only JFIF, but not variations such as EXIF, SPIFF, Adobe JPEG and other

### ISSUE THREAD

**Issue by Elvyria** [3rd/image.nvim#131]
Hi. Image in my markdown file wasn't showing up and I found out that `image.nvim` doesn't detect it as image, because [magic.lua](https://github.com/3rd/image.nvim/blob/147bbe661bdec4a16a93fbd1f08a43040c363942/lua/image/utils/magic.lua#L7) only detects *.jpg* files with the header of `FF D8 FF E0` which refers only to **JPEG/JFIF** version of JPEG.

My file header is `FF D8 FF E1` - **JPEG/EXIF**.

Since there are multiple different ways of solving this issue I come with an issue and not a PR.
* Could limit `FF D8 FF E0` to `FF D8 FF` potentially marking unsupported image types as supported.
* Could specify all tested/supported variations of JPEG.
* Could also include file tail (`FF D9` for JPEG) for checking.

Useful related links:
https://www.garykessler.net/library/file_sigs.html
http://www.faqs.org/faqs/jpeg-faq/part1/section-15.html
https://en.wikipedia.org/wiki/List_of_file_signatures

(Also, please consider moving log file from `/tmp` to `vim.fn.stdpath('log')`, i like them, they are useful)

**Comment by 3rd** [comment]
Hi @Elvyria, thanks for the issue!
I created a PR to fix this by mixing your first point with the last one, should be ok, right?
https://github.com/3rd/image.nvim/pull/133

**Comment by Elvyria** [comment]
Yes, it works, thank you.
Could you just please not open/close file twice and change `read_file_header` and `has_jpeg_end_signature` to accept file descriptor instead of a path (that should also save you some checks and lines of code)?

**Comment by 3rd** [comment]
Done, thank you!
