### ISSUE TITLE
Render same image object multiple times

### ISSUE THREAD

**Issue by Poly2it** [3rd/image.nvim#146]
I am working on a project where it would be very useful if one could render the same image object multiple times on the screen. You would create a single instance of the image object, which could then be stamped multiple times. [This is how kitty handles images](https://sw.kovidgoyal.net/kitty/graphics-protocol/#display-images-on-screen), so it would make a lot of sense to extend the API in this way. It would also be more performant (I really need performance for the project I'm working on).

**Comment by 3rd** [comment]
Hey, what's your use case & what exactly do you need to optimize?
Currently we do some unnecessary things when using Kitty, but I'm trying to get rid of all that in the rewrite.
We do attempt to track transmitted images and try not to transmit them again.

**Comment by Poly2it** [comment]
> Hey, what's your use case & what exactly do you need to optimize? Currently we do some unnecessary things when using Kitty, but I'm trying to get rid of all that in the rewrite. We do attempt to track transmitted images and try not to transmit them again.

I am creating a file drawer in which I will need to draw repetitive data, the icons. Perhaps image should more directly mirror the Kitty functionality? Kitty images are very simple, being represented as a single reference integer, so mirroring and exposing that as a core API would contribute a lot of value in simplicity to the project, if you're doing a rewrite anyway.

**Comment by 3rd** [comment]
Definitely not gonna have that API, but if you create another image that has the same source it shouldn't be transmitted twice if you don't clear it "deeply".
You can write any abstraction you might find better for your use case on top of the kitty rendering helpers.

**Comment by Poly2it** [comment]
> Definitely not gonna have that API, but if you create another image that has the same source it shouldn't be transmitted twice if you don't clear it "deeply". You can write any abstraction you might find better for your use case on top of the kitty rendering helpers.

Okay.
