### ISSUE TITLE
renderer.lua: attempt to index a nil value

### ISSUE THREAD

**Issue by simonecig** [3rd/image.nvim#152]
Hello, commit 88566b broke this plugin completely for me. Whenever I try to render an image in Kitty I get the following error 
`pynvim.api.common.NvimError: Error executing lua: /home/simo/.config/nvim/image.nvim/lua/image/renderer.lua:321: attempt to index a nil value `
I think that the problem is that the property "date:modify" does not exist on my machine (while I can still access other properties)
`print(magick_image:get_property("png:IHDR.bit_depth")) -- prints 8 `
`print(magick_image:get_property("date:modify")) -- prints nil 0`

I'm on NixOS 23.11 (which could very well be the problem...) and I installed everything following the vanilla NixOS guide (i.e. through `neovimUtils.makeNeovimConfig`)

Neovim version is 0.9.4
ImageMagick v7.1.1-29
I do not know how to get the version of magick when installed in this way.

Please let me know if you need further information.

**Comment by 3rd** [comment]
Hey, sorry about that, was fixed yesterday with a revert.
