### ISSUE TITLE
How to toggle markdown image previews with a command? 

### ISSUE THREAD

**Issue by MikeLemo1** [3rd/image.nvim#181]
I'm trying to toggle image preview on and off in a markdown file to scan scroll it faster and I'm now sure this feature is available is it?
if not i'd be helpful to know how refined / not this project is to know how to approach feature dev and bug rectification in the future

**Comment by 3rd** [comment]
Hey, here's a sample for clearing / rerendering from Discord:

```lua
local api = require("image")

local bufnr = vim.api.nvim_get_current_buf()
local images = api.get_images({ buffer = bufnr })
for _, image in ipairs(images) do
  image:clear(true)
end

vim.keymap.set("n", "<leader>x", function()
  for _, image in ipairs(images) do
    image:render()
  end
end)
```

**Comment by MikeLemo1** [comment]
```lua title="3rd/image config"
vim.keymap.set({ "n", "v" }, "<leader>pt", function()
          local bufnr = vim.api.nvim_get_current_buf()
          local images = api.get_images({ buffer = bufnr })
          for _, image in ipairs(images) do
            image:clear(true)
          end
          end, opts) 
```
This doesn't hide the image but just blinks it when ++<leader>-p-t++

**Comment by 3rd** [comment]
@MikeLemo1 Try this branch please: https://github.com/3rd/image.nvim/pull/182

```lua
local api = require("image")

vim.keymap.set({ "n", "v" }, "<c-c>", function()
  api.disable()
end, {})

vim.keymap.set({ "n", "v" }, "<c-x>", function()
  api.enable()
end, {})
```

**Comment by MikeLemo1** [comment]
with lazy plugin manager:
```lua
{
      "3rd/image.nvim",
      branch = "feat/toggle-rendering",
    config = function()
    local api = require("image")

    vim.keymap.set({ "n", "v" }, "<leader>pc", function()
      api.disable()
    end, {})

    vim.keymap.set({ "n", "v" }, "<leader>po", function()
      api.enable()
    end, {})
    end,
}
```
Does the trick!

BTW Whatbout the image offset? it also might require "padding offset" as it can also be reduced one column less for more "page efficiecy"

**Comment by 3rd** [comment]
Ah it's complicated, can look into it after finishing the first rewrite.

**Comment by Jab2870** [comment]
Thanks for this. Anyone coming here looking for a toggle command, @3rd also exposed an is_enabled api function, so I have

```lua
		vim.keymap.set("n", "<leader>ti", function()
			if image.is_enabled() then
				image.disable()
			else
				image.enable()
			end
		end, {})
```

**Comment by xuwei152** [comment]
@3rd 
Will branch  "feat/toggle-rendering" be merged to the master branch?


> with lazy plugin manager:
> 
> ```lua
> {
>       "3rd/image.nvim",
>       branch = "feat/toggle-rendering",
>     config = function()
>     local api = require("image")
> 
>     vim.keymap.set({ "n", "v" }, "<leader>pc", function()
>       api.disable()
>     end, {})
> 
>     vim.keymap.set({ "n", "v" }, "<leader>po", function()
>       api.enable()
>     end, {})
>     end,
> }
> ```
> 
> Does the trick!
> 
> BTW Whatbout the image offset? it also might require "padding offset" as it can also be reduced one column less for more "page efficiecy"
