### ISSUE TITLE
Display local gifs with ueberzug

### ISSUE THREAD

**Issue by MikeLemo1** [3rd/image.nvim#186]
I'm using ueberzug and I am able to view images and svg's but local gifs appear as small black rectangle and online gifs such as:
`![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)`
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)
only show the first picture of the gifs and freeze(I assume)

previewing the same gifs in vifm with ueberzug does work though.
unless there are two versions of ueberzug on my pc and vifm and image each use different version it's probably not ueberzug.

also in markdown image links don't get detected and previewed automatically after typing the link unless I save the file and restart nvim...

Reference to the local gif file I'm trying to run:
https://github.com/ray-x/files/raw/master/img/navigator/show_signnature.gif?raw=true

![](https://github.com/ray-x/files/raw/master/img/navigator/show_signnature.gif?raw=true)

**Comment by 3rd** [comment]
Hey, ueberzug is a second class citizen due to being slow and we don't support animations yet, we convert all images to PNG.
Will probably support this in the next version.

**Comment by MikeLemo1** [comment]
Huh that's racist just because I don't want to touch the degenerate parasite kitty doesn't mean I need to treated like a second class citizen!!!! 
Anyhow I thought it does some direct rendering and inlay on terminal tiles with ueberzug directly with it's engine, looks like this repo is gonna need a lot of refinement...

**Comment by 3rd** [comment]
> also btw if we are already in it how is the "Virtual padding" spaces created for the images called in the nvim terminology or some nvim plugin term?
:h extmark
