### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by jessevdp** [3rd/image.nvim#187]
Hey, I'm having some trouble with images not displaying.

(I'm using Alacrity on MacOS.)

Initially I had trouble with getting everything installed correctly. I followed some steps from https://github.com/3rd/image.nvim/issues/91 and got the `minimal-setup.lua` running without errors.

I can see that there are lines being reserved for the image to display (3 lines without line number, then line number 4). It just... isn't rendering.

<img width="1368" alt="Screenshot 2024-06-28 at 13 13 04" src="https://github.com/3rd/image.nvim/assets/15139826/8b5e0e07-99d4-4850-86a9-74fda57f4ef7">

---

To make sure I got the simplest reproduction case I'm not even running this inside of Tmux or anything.

Perhaps a long shot... but any clue where I might need to look next?

---

Some version info:

```
Alacrity version 0.13.2

➜ nvim -v
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

➜ magick -version
Version: ImageMagick 7.1.1-34 Q16-HDRI x86_64
```

Thanks for your time & help!

**Comment by 3rd** [comment]
Hey, the plugin uses Kitty's graphics protocol or ueberzug++ for rendering, you need to set one of those up (works much better with Kitty).

**Comment by jessevdp** [comment]
Ah thanks! I don't know why... but I was under the impression that Alacrity would have it setup or something.

My bad! Sorry.
