### ISSUE TITLE
adjust_to_aspect_ratio ignores max_width/height

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#19]
In the renderer, we crush the image down to `max_width` and `max_height` before fixing the aspect ratio. In fixing the aspect ratio, we then ignore the max width/height allowing one of the max values to be exceeded.

This problem I think is made worse by choosing to keep the larger of the width and height and adjust the smaller value? Just fixing this issue made the `max_width/height` values behave pretty much how I expected them to, although I know there are edge cases that need a more thorough solution.  

I think that more thorough solution would be to keep the value that gets reduced the most. This way the other value with always shrink, and therefore cannot exceed it's max value.

I'm happy to submit a PR if the things that I'm saying make sense.

**Comment by 3rd** [comment]
It makes total sense, thank you for catching this!
If you already made the change it please open a PR.

Unrelated, are you using the plugin with Kitty and what are you using it for?
I'm working on a refactor to make the API more friendly to make things like https://github.com/3rd/image.nvim/issues/17 possible, and refactoring the document syntax integrations as well. Do you have any suggestions or things you'd wish for?

Thanks again for the contribution!

**Comment by benlubas** [comment]
I'm running wezterm + tmux these days. I'm a student in a class where I have to work with jupyter notebooks with matplotlib. I'm trying to get my setup into a good spot so that I can work on that stuff pretty seamlessly from neovim. 

I chose to use magma-nvim for the jupyter kernel and code running, which is working great, but the magma implementation of kitty image protocol is a little buggy and I'm not trying to fix that, I'd rather just outsource the work of rending images to this plugin.

**Comment by 3rd** [comment]
That's super cool and Magma looks sick!
