### ISSUE TITLE
Image appears Rotated by 90 degrees every time I open it with neovim

### ISSUE THREAD

**Issue by utkarsh-20-rajput** [3rd/image.nvim#195]
Everytime I open an image, it appears rotated by 90 degrees. I am on Linux Mint and use Neovim with Lazy.nvim on Wezterm. I don't use tmux.

Here's my magick.lua file
`return {
  "3rd/image.nvim",
  dependencies = {
    "leafo/magick",
    {
      "nvim-treesitter/nvim-treesitter",
      build = ":TSUpdate",
      config = function()
        require("nvim-treesitter.configs").setup({
          ensure_installed = { "markdown" },
          highlight = { enable = true },
        })
      end,
    },
  },
  -- default config
  config = function()
    require("image").setup({
      backend = "ueberzug",
      integrations = {
        markdown = {
          enabled = true,
          clear_in_insert_mode = false,
          download_remote_images = true,
          only_render_image_at_cursor = true,
          filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
        },
        neorg = {
          enabled = true,
          clear_in_insert_mode = false,
          download_remote_images = true,
          only_render_image_at_cursor = false,
          filetypes = { "norg" },
        },
        html = {
          enabled = true,
        },
        css = {
          enabled = true,
        },
      },
      max_width = nil,
      max_height = nil,
      max_width_window_percentage = nil,
      max_height_window_percentage = 50,
      window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
      window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
      editor_only_render_when_focused = true, -- auto show/hide images when the editor gains/looses focus
      tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)
      hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.avif" }, -- render image files as images when opened
    })
  end,
}`

and img-clip.lua
`return {
  "HakonHarnes/img-clip.nvim",
  event = "VeryLazy",
  opts = {
    -- add options here
    -- or leave it empty to use the default settings
  },
  keys = {
    -- suggested keymap
    { "<leader>p", "<cmd>PasteImage<cr>", desc = "Paste image from system clipboard" },
  },
}`

I also use smart-splits and treesitter if it helps

**Comment by 3rd** [comment]
This is super weird, must be something weird with Wezterm.
Can you reproduce it with Kitty?

**Comment by utkarsh-20-rajput** [comment]
Before using wezterm, I was using Alacritty with tmux. Faced no issues.

**Comment by 3rd** [comment]
Sorry, there's nothing we can do, Wezterm has a wonky implementation of the Kitty graphics protocol.
On Alacritty you must've used ueberzug, you should still be able to do that with Wezterm, but the performance is not going to be great.

**Comment by utkarsh-20-rajput** [comment]
I am using ueberzug not kitty backend.

**Comment by 3rd** [comment]
Super weird, best guess is some weird interaction between wezterm and ueberzug.
You can try logging [here](https://github.com/3rd/image.nvim/blob/master/lua/image/backends/ueberzug.lua#L67) to get the processed image path, and if it looks normal it must be wez+ueberzug being weird.

**Comment by utkarsh-20-rajput** [comment]
thanks for the help 😁
I'll switch to alacritty i guess

**Comment by 3rd** [comment]
come to kitty, join the dark side :joy:
