### ISSUE TITLE
How to set a maximum image size

### ISSUE THREAD

**Issue by CRAG666** [3rd/image.nvim#2]
First of all amazing work, I plan to use it in my day to day but I would like to know how to set a maximum size

**Comment by 3rd** [comment]
Hey, currently you can set a max size from the configuration you pass in the setup call: https://github.com/3rd/image.nvim#configuration

`max_width` and `max_height` are in cells and apply for all images in any context
`max_width_window_percentage` and `max_height_window_percentage` apply to images bound to a window

Only `max_height_window_percentage` is set by default to 50%.
Let me know if it works and if you have any ideas to improve it!
