### ISSUE TITLE
Image doesn't show up in neovide

### ISSUE THREAD

**Issue by horanmustaplot** [3rd/image.nvim#203]
I just cannot see the image in neovide, but in kitty it works pretty good.

**Comment by 3rd** [comment]
Hey, Neovide is a GUI app, we only support terminals.

**Comment by linkarzu** [comment]
@aehabdelouadoud  you can disable image.nvim in Neovide to avoid that error when you open it, I do that in the disabled.lua file. I use the lazyvim.org distro
- I have a [video for this](https://youtu.be/rNYtfA4zlO4)

<div align="left">
    <a href="https://youtu.be/rNYtfA4zlO4">
        <img
          src="https://github.com/user-attachments/assets/9cc5a0f1-632d-44c0-92d1-3952cdc36de7"
          alt="My complete Neovim markdown setup and workflow in 2024"
          width="400"
        />
    </a>
</div>
