### ISSUE TITLE
Uberzug backend dosen't work in xfce4-terminal

### ISSUE THREAD

**Issue by cofeek-codes** [3rd/image.nvim#205]
my specs are
```
OS: Fedora Linux 39 (Thirty Nine) x86_64 
Terminal: xfce4-terminal 
CPU: AMD Ryzen 5 5600G with Radeon Graphics (12) @ 4.464GHz 
GPU: NVIDIA Geforce RTX 3050
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
lazy.nvim version: 11.14.1 
ueberzugpp 2.9.6
Lua 5.1  Copyright (C) 1994-2006 Lua.org, PUC-Rio
```
my config is: 
```lua
return {
  "3rd/image.nvim",
  dependencies = {
    "leafo/magick",
    "nvim-treesitter/nvim-treesitter",
    {
      "vhyrro/luarocks.nvim",
      config = function()
        require("image").setup({
          backend = "ueberzug",
          kitty_method = "normal",
          integrations = {
            markdown = {
              enabled = true,
              clear_in_insert_mode = false,
              download_remote_images = true,
              only_render_image_at_cursor = false,
              filetypes = { "markdown", "vimwiki" }, -- markdown extensions (ie. quarto) can go here
            },
            neorg = {
              enabled = true,
              clear_in_insert_mode = false,
              download_remote_images = true,
              only_render_image_at_cursor = false,
              filetypes = { "norg" },
            },
            html = {
              enabled = false,
            },
            css = {
              enabled = false,
            },
          },
          max_width = nil,
          max_height = nil,
          max_width_window_percentage = nil,
          max_height_window_percentage = 50,
          window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
          window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
          editor_only_render_when_focused = false, -- auto show/hide images when the editor gains/looses focus
          tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)
          hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.avif" }, -- render image files as images when opened
        })
      end,
      opts = {
        rocks = {
          hererocks = true,
        },
      },
    },
  },
}

```
It works well in kitty, but kitty has wierd font bugs on my system so i want to use other terminal (xfce4-terminal in my case), but when i open image there i get just an empty buffer. 

`xfce4-terminal`

![2024-08-13-184131_1920x1080_scrot](https://github.com/user-attachments/assets/8ddf9029-7395-43d2-a079-2cd51867cae0)
`kitty`

![2024-08-13-184154_1920x1080_scrot](https://github.com/user-attachments/assets/cbc7a78b-ac8e-437b-b247-725a77ce00dc)

**Comment by cofeek-codes** [comment]
i also noticed when plugin try to render image in markdown it throws this error 
```
 Error executing vim.schedule lua callback: Vim:E474: Unable to represent NaN value in JSON
stack traceback:
	[C]: in function 'json_encode'
	...are/nvim/lazy/image.nvim/lua/image/backends/ueberzug.lua:29: in function 'write'
	...are/nvim/lazy/image.nvim/lua/image/backends/ueberzug.lua:67: in function 'render'
	....local/share/nvim/lazy/image.nvim/lua/image/renderer.lua:462: in function 'render'
	...ek/.local/share/nvim/lazy/image.nvim/lua/image/image.lua:55: in function 'render'
	.../share/nvim/lazy/image.nvim/lua/image/utils/document.lua:88: in function 'render_image'
	.../share/nvim/lazy/image.nvim/lua/image/utils/document.lua:121: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

**Comment by 3rd** [comment]
The JSON issue is an interesting bug, are you rendering a SVG by any chance?
The ueberzugpp issue might be related, but unsure how to reproduce it.

Kitty's performance is much better, what issues do you have with font rendering?

**Comment by cofeek-codes** [comment]
when i try to open jpg/png i am getting this json error, when i open svg file it opens as plain text

**Comment by cofeek-codes** [comment]
![image](https://github.com/user-attachments/assets/87819210-f5cc-45b9-8588-5b995a887f6d)
about wierd bugs in kitty: i have  same font in kitty and xfce4-terminal, but in kitty some of the icons in neovim are not displayed correctly

here is my `kitty.conf`:
```conf
font_family 	FiraCode Nerd Font Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 18.0

background_opacity 0.85

map ctrl+shift+t new_tab_with_cwd

window_padding_width 15

tab_bar_style custom

shell_integration no-cursor

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

```

**Comment by 3rd** [comment]
Either:
- Kitty doesn't find the fallback font your other terminal does, and that one contains the icons.
- Kitty doesn't load `FiraCode Nerd Font Regular` because it's not a monospace font.

To debug what happens run `kitty --debug-font-fallback` and it will print out which font is using for which glyphs, as they are renderer (open nvim in the debug terminal). 

It's probably because the font is not monospaced: https://github.com/ryanoasis/nerd-fonts/discussions/1039

**Comment by cofeek-codes** [comment]
yeah i was setting the font in a wrong way. i am sorry to bother you with it. So i configured kitty and moved there. works fine exept svgs. they're rendered as text

**Comment by 3rd** [comment]
No worries, I spent a lot of time debugging fonts as well.
If you want SVGs to work you need to add `"*.svg"` to `hijack_file_patterns` in the options, it's disabled by default because people might want to edit them.
