### ISSUE TITLE
Config fails when run outside terminal (i.e. using nvim-qt)

### ISSUE THREAD

**Issue by ejb-11** [3rd/image.nvim#210]
The plugin works fine when run in a terminal (I am using the Überzug backend on st) after a bit of fighting with it to do with luarocks which I eventually worked out (I am using lazy.nvim). Since I am a brand-new user to Neovim I wasn't familiar with lua but I eventually worked out that the luarock path lines from the readme.md go in the init.lua.

Anyway, it doesn't work in nvim-qt (haven't tested in any other GUIs). It fails with this message:
```
Failed to run `config` for image.nvim

...ocal/share/nvim/lazy/image.nvim/lua/image/utils/term.lua:34: Failed to get terminal size

# stacktrace:
  - /image.nvim/lua/image/utils/term.lua:34 _in_ **update_size**
  - /image.nvim/lua/image/utils/term.lua:46
  - /image.nvim/lua/image/utils/init.lua:8
  - /image.nvim/lua/image/utils/init.lua:1
Press ENTER or type command to continue
```
If I ignore that and try to test it by opening an image file, it falls through to the normal nonsense characters (because image.nvim hasn't been loaded presumbably).

I don't know if this could be easily fixed (probably not since I imagine checking the window size is more annoying than terminal size), but if not perhaps it would be a good idea to have a small note on the readme.md about it only working in a terminal, not a GUI version.

Thanks.

**Comment by 3rd** [comment]
Yeah, I'll add a note to the README to make it clearer that it's terminal-only (and that there's no official support for anything macOS/Wezterm related, that's also popping up a lot)

**Comment by leiserfg** [comment]
@3rd it would be nice to not show this error tho, it happens also when running as a children of some apps, even when running inside of a terminal (jjui for intsance), and it's a bit annoying.
