### ISSUE TITLE
Minimal setup works but others don't

### ISSUE THREAD

**Issue by keijiu** [3rd/image.nvim#219]
Hi

I'm having trouble rendering images in my own setup and own markdown files.

The minimal-setup.lua works from my end, which could probably prove something like "imagemagick" and "magic rock" are installed correctly.
<img width="713" alt="Screenshot 2024-09-24 at 10 05 38 AM" src="https://github.com/user-attachments/assets/fe8f9ea2-dd10-47e6-b639-65411f10c341">

However it doesn't work in my own Neovim. 
<img width="724" alt="Screenshot 2024-09-24 at 10 11 14 AM" src="https://github.com/user-attachments/assets/c462c468-b633-4458-a54f-fcb342173b8d">

The config of image.nvim is attached below, which I just copy and paste. 
![Uploading Screenshot 2024-09-24 at 10.16.29 AM.png…]()

No error occurs in my Neovim. Just not render images. I watched a youtube video regarding not rendering images in his Obsidian. The youtuber claims that it happens because image.nvim can't locate where the images come from in the Obsidian and finally modifies the "current_image.url" to his local path. I'm not using Obsidian. I don't know if it is the same reason and I don't know how to work around it.

I appreciate you time and help

**Comment by KayjiYu** [comment]
<img width="719" alt="Screenshot 2024-09-24 at 10 16 29 AM" src="https://github.com/user-attachments/assets/541cda82-bc04-4bc4-bd5b-e86c12b055d8">

**Comment by 3rd** [comment]
Hey, does it happen when there are other non-image lines at the beginning of the document?
It might be a bug with images on the first line of the buffer.

**Comment by KayjiYu** [comment]
It works after adding a line of text above. Thank you very much!
<img width="1012" alt="Screenshot 2024-09-24 at 3 25 06 PM" src="https://github.com/user-attachments/assets/643e1707-5565-4238-8fff-b3e5e1c405e6">

**Comment by KayjiYu** [comment]
It works after adding a line of text above. Thank you very much!
<img width="1012" alt="Screenshot 2024-09-24 at 3 25 06 PM" src="https://github.com/user-attachments/assets/996c2d37-876c-40cc-b5e9-aea204912bf8">

**Comment by 3rd** [comment]
So it's that bug I forgot about about, sorry :blush: 
Will fix it soon, I'll keep this open until it's handled.

**Comment by 3rd** [comment]
Should be fixed now.
