### ISSUE TITLE
Not recommended to export DYLD_LIBRARY_PATH ?

### ISSUE THREAD

**Issue by gbelouze** [3rd/image.nvim#222]
Hi, first of all thanks for this very useful plugin.

I followed the install instruction as a mac user and notable ran
```bash
export DYLD_LIBRARY_PATH="$(brew --prefix)/lib:$DYLD_LIBRARY_PATH"
```

Do you mind providing more context as to why this is needed ? On my side
- `image.nvim` worked fine without this export on the latest version of homebrew
- exporting DYLD_LIBRARY_PATH made me run into issues unrelated to `image.nvim`, see for instance https://github.com/apache/arrow/issues/44244

**Comment by 3rd** [comment]
Hey, if it works without that we should remove it.
The macOS-specific instructions are a mix of things that worked for different users.

**Comment by 3rd** [comment]
Fixed in https://github.com/3rd/image.nvim/pull/230
Added a mention that's only for some users, thank you!
