### ISSUE TITLE
Images do not render while in a poetry shell.

### ISSUE THREAD

**Issue by Blvve** [3rd/image.nvim#225]
Hi, I have noticed that images do not render while in a poetry shell. There is no issue when the virtual environment is created without poetry.

![no poetry](https://github.com/user-attachments/assets/a8db5535-9d74-489c-a889-0a68e70819fe) ![poetry](https://github.com/user-attachments/assets/c20acbc7-7afd-401e-ab54-c07bcbfdd85d)

I still have the issue with this minimal neovim config
```
local plugins = {
  {
    "3rd/image.nvim",
    dependencies = {
      'leafo/magick',
    },
    config = true
  },
}

-- bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
local opts = {}
require("lazy").setup(plugins, opt)
```
I use kitty with arch linux.

**Comment by sankantsu** [comment]
It's weired. In my case, image shows up, but image size was incorrect.

<img width="1470" alt="Screenshot 2024-11-02 13 22 26" src="https://github.com/user-attachments/assets/e8f8fed5-bd82-4316-8dfb-de421586f5da">

I created simple [script](https://gist.github.com/sankantsu/3621ee3d17fb6c6305f0cff26931f3d8) (based on [kitty's code](https://github.com/kovidgoyal/kitty/blob/847433dba2271031cd7d58025022eef10a668072/tools/tty/tty.go#L348)) to get terminal and pixel size and did some experiment.
It seems that in `poetry shell` or `pipenv shell` etc, new pseudo terminal is allocated for the shell.
In that pseudo terminal, kitty cannot get correct terminal pixel sizes and fail to render image in appropriate sizes.

<img width="1470" alt="Screenshot 2024-11-02 13 17 58" src="https://github.com/user-attachments/assets/0a8ebef4-f9fa-42ab-a2ce-b73f48cf7225">

MacOS 13.7 and KItty version is `0.36.4`.

**Comment by 3rd** [comment]
I guess it's not something we can / should handle, right?

**Comment by sankantsu** [comment]
The essential problem seems that we cannot get correct terminal size in pixels with `ioctl()` inside environment like `poetry shell`. image.nvim also use `ioctl()` for getting terminal size in pixel.
https://github.com/3rd/image.nvim/blob/25676deed3d5cba3d8dda0f2a0e9c0b71a4aaab6/lua/image/utils/term.lua#L34

Eventually `image_rows` (`renderer.lua`) becomes `inf`, and I guess it leads incorrect image size or complete disappearance of images.
https://github.com/3rd/image.nvim/blob/25676deed3d5cba3d8dda0f2a0e9c0b71a4aaab6/lua/image/renderer.lua#L14


We cannot change `ioctl()` behavior in this plugin code, so basically we can not handle this problem, I think.

Possible workaround is to get terminal size in some different way.
There is a control sequence (`\x1b[14t`) to get terminal size in pixels. (c.f. [xterm control sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_))
It seems that this control sequence can correctly get size in pixels even when I am in `poetry shell` environment.

**Comment by 3rd** [comment]
I'd say it's out of scope, thanks for the investigation @sankantsu!
