### ISSUE TITLE
Image Alignment Issues in Typst

### ISSUE THREAD

**Issue by etiennecollin** [3rd/image.nvim#232]
Good evening,
I recently added support for `typst` files, but I've encountered an issue with image positioning. While images typically appear correctly, there are instances where they don’t align properly. In these cases, the appropriate space is allocated, but the images are mispositioned too high in the editor.

It seems like, even when I restart nvim, it's always the same images in a given document that cause the issue (i.e. the images that render correctly continue to do so, while those that do not are consistently misaligned).

Interestingly, I haven't experienced this problem with markdown files (even with the problematic typst images).

I would greatly appreciate any insights you might have on what could be causing this inconsistency. I've included two examples showcasing the improper rendering, along with one where the image is displayed correctly.

Thank you for your help, I look forward to solving this issue!

## NOT Working Examples
<img width="1800" alt="Screenshot 2024-10-28 at 20 52 15" src="https://github.com/user-attachments/assets/2d4878c4-fed7-4e85-86b2-7896fcbe725e">
<img width="1800" alt="Screenshot 2024-10-28 at 20 55 58" src="https://github.com/user-attachments/assets/9abd69e5-7d8a-4e80-84f4-e769fea6c5a8">

## Working Example
<img width="1798" alt="Screenshot 2024-10-28 at 20 56 10" src="https://github.com/user-attachments/assets/96e0fcfc-3b35-4546-82c6-e8486821dca5">

**Comment by 3rd** [comment]
Hello, can you please share an example source file where it's not working?
Also, do you have by any chance plugins that modify the winbar?

**Comment by etiennecollin** [comment]
Hi,
I don't think I have any plugins modifying the winbar.

Here is what I see on my screen with kitty:
<img width="1912" alt="Screenshot 2024-10-28 at 22 10 32" src="https://github.com/user-attachments/assets/dabce078-57e4-4087-b874-c5779c684dff">

And here is the content:
```typst
= Test

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

#figure(
  image("https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.media.io%2F2022%2Funblur-image-online-banner.png&f=1&nofb=1&ipt=d8bda83dabf537b5f48687afa100799ce825c5cc93033e5ff11031e67781c480&ipo=images", width: 80%),
) <fig-circuit_1>

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Comment by etiennecollin** [comment]
I just noticed I can produce a similar error in markdown files
<img width="1912" alt="Screenshot 2024-10-28 at 22 30 04" src="https://github.com/user-attachments/assets/6e675ae7-a777-4657-a735-1a60c8aa692c">

Content:
```md
# Test

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

![test](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.media.io%2F2022%2Funblur-image-online-banner.png&f=1&nofb=1&ipt=d8bda83dabf537b5f48687afa100799ce825c5cc93033e5ff11031e67781c480&ipo=images)

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

**Comment by etiennecollin** [comment]
Here is my kitty config:

```conf
include ./gruvbox.conf # This is just my theme

macos_option_as_alt left
font_family      Maple Mono NF
font_features    MapleMono-NF-Regular zero cv01 cv02 ss03
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16.0
tab_bar_style separator
tab_bar_align center
tab_separator " | "
enabled_layouts splits
allow_remote_control yes
```

And my image.nvim config:
```lua
return {
	"3rd/image.nvim",
	ft = { "markdown", "vimwiki", "html", "typst" },
	dependencies = {
		"leafo/magick",
	},
	opts = {
		backend = "kitty",
		kitty_method = "normal",
		integrations = {
			typst = {
				enabled = true,
				clear_in_insert_mode = true,
				download_remote_images = true,
				only_render_image_at_cursor = true,
			},
			html = {
				enabled = true,
				clear_in_insert_mode = true,
				download_remote_images = true,
				only_render_image_at_cursor = true,
			},
			markdown = {
				enabled = true,
				clear_in_insert_mode = true,
				download_remote_images = true,
				only_render_image_at_cursor = true,
				filetypes = { "markdown", "vimwiki" },
			},
		},
		max_width = nil,
		max_height = nil,
		max_width_window_percentage = 50,
		max_height_window_percentage = 50,
		-- auto show/hide images when the editor gains/looses focus
		editor_only_render_when_focused = false,
		-- toggles images when windows are overlapped
		window_overlap_clear_enabled = true,
		window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
		-- auto show/hide images in the correct Tmux window (needs visual-activity off)
		tmux_show_only_in_active_window = true,
	},
}
```

**Comment by 3rd** [comment]
Ah I tested it now, I think it's because of wrapping. Does it work ok if you `:set nowrap`?
If it's the wrapping then we don't support that yet, there is an idea on how to do it in https://github.com/3rd/image.nvim/issues/62#issuecomment-2250831591

**Comment by etiennecollin** [comment]
Thank you for your help! That fixes the issues in kitty.

I still get render issues in wezterm, but I will open another issue for that at some point to stay on-topic.
Have a great evening!
