### ISSUE TITLE
Undefined variable: s:output

### ISSUE THREAD

**Issue by Pukimaa** [3rd/image.nvim#240]
Hey. Builds keep failing.

Here's the error:
`/redacted/.config/nvim/init.lua..function health#report_error[4]..<SNR>6_collect_output, line 1: Vim(let):E121: Undefined variable: s:output`

**Comment by 3rd** [comment]
Hey, is this for the minimal setup or your regular config?

**Comment by Pukimaa** [comment]
> Hey, is this for the minimal setup or your regular config?

minimal setup i suppose. it's just listed as the dependency of neotree :)

**Comment by 3rd** [comment]
Can't figure out anything from that error message, going to close this.
Please go over the readme again, try the magick_cli provider and disable building. The only kind of build this plugin can trigger is the one for the rock.
Feel free to pop in the Discord for help.
