### ISSUE TITLE
Images spawn on every tmux panes.

### ISSUE THREAD

**Issue by S0mbr3** [3rd/image.nvim#25]
Hello and thanks for this, for the first time we are getting real images integration into Neovim !

I don't know if it's a bug of my own since it is not specified anywhere, but when opening md/norg files in neovim from tmux, the images  are exactly as it should be in the files. But they also spawn into every tmux panes as a background also.

I have the last kitty/neovim/tmux versions with default setup for image.nvim and enabling the passthrough in tmux with "set -g allow-passthrough on"

**Comment by 3rd** [comment]
Hey, yes, there's no handling for tmux pane switching yet, but it's on the list!

**Comment by benlubas** [comment]
@3rd have you looked into this at all? If you have any info on where to start supporting something like this I'd be more than happy to tackle it. 

Starting to grow tired of switching tabs and then having to go back to close an image

If you haven't looked at this at all I'm also happy to look into it, just thought I'd ask first.

**Comment by 3rd** [comment]
Couldn't find a way to do it without adding a tmux script, still exploring.

**Comment by 3rd** [comment]
@benlubas would it be acceptable to hide/show the images on nvim focus lost/gained? It would also hide them when switching to a different pane in the same window.

**Comment by benlubas** [comment]
Yeah my first thought was focus lost/gained, personally I wouldn't have a problem with images disappearing when switching panes but I could see why others might. 

I wonder what notcurses does.. maybe we can ask dank

**Comment by benlubas** [comment]
I've tried a simple implementation with focus lost, and it's unfortunately not working.

(`P()` is a function that prints using vim.inspect)

```lua
if state.options.tmux_mode then
  local held_images = {}
  print("tmux mode")
  -- hide all images on focus lost
  vim.api.nvim_create_autocmd("FocusLost", {
    group = group,
    callback = function(_au)
      print("focus lost")
      vim.schedule(function()
        held_images = api.get_images()
        P(held_images)
        for _, current_image in ipairs(held_images) do
          current_image:clear()
        end
      end)
    end,
  })
  -- re-render on focus gained
  vim.api.nvim_create_autocmd("FocusGained", {
    group = group,
    callback = function(_au)
      print("focus gained")
      for _, current_image in ipairs(held_images) do
        current_image:render()
      end
    end,
  })
end

```

**Comment by 3rd** [comment]
Added a new option `editor_only_render_when_focused` in https://github.com/3rd/image.nvim/commit/133926c01bb5160b6ff26c37891e7d8a1d73528f that should be an ok workaround until we figure something else out ; it's not tied to Tmux in any way, just a general option.

The more advanced way would be to make a plugin for Tmux that sends a message to nvim, either through the remote protocol (would require remote control enabled), by sending keys (yuck), or by writing to a socket file (probably).

I think it's good enough for now.

**Comment by 3rd** [comment]
Reopening, doesn't seem to work properly, looking into it.

**Comment by benlubas** [comment]
Haha, I beat you to it. That implementation works for focus via window manager, but tmux switching, while it triggers the auto command, doesn't actually clear the image.

**Comment by 3rd** [comment]
The Neovim part seems ok, it's a clearing issue, which is better than the events not working. I think it doesn't have time to output the escape codes for clearing.

https://github.com/3rd/image.nvim/assets/59587503/a694724c-12ca-4fd6-9c48-6f38d71b8a3e

**Comment by benlubas** [comment]
@dankamongmen does notcurses do anything special to handle switching panes in tmux?

**Comment by dankamongmen** [comment]
> @dankamongmen does notcurses do anything special to handle switching panes in tmux?

nope, very little tmux-specific code

**Comment by 3rd** [comment]
Found a way to do it by finding the active tty for the current tmux session and writing Kitty's clear-all control sequence in that one. It's hacky, but it works. Just needs some changes to make the "restore" work.

**Comment by 3rd** [comment]
Linking PR: https://github.com/3rd/image.nvim/pull/45

**Comment by 3rd** [comment]
This is now in `master`, needs `tmux_show_only_in_active_window = true` and `set -g visual-activity off` in Tmux :tada:

**Comment by petobens** [comment]
Hi! In the following gif I open a split (pane) I see the image in the pane below  (even though I'm using the `tmux_show_only_in_active_window` setting):

![Peek 2023-10-31 19-10](https://github.com/3rd/image.nvim/assets/2583971/d323c580-bb78-4494-99b8-3553dcec5c51)

**Comment by 3rd** [comment]
Yes, it only handles window switching, with a massive hack. In theory it could handle panes as well, need to check.
