### ISSUE TITLE
Image shows perfect once, second or more times it does not show

### ISSUE THREAD

**Issue by resistorsoftware** [3rd/image.nvim#251]
I open NeoVim from Kickstart, with image.nvim working using luarocks and Markdown files show images fine. I can close the file and re-open it, images work. 

But if I select a file using the tree, sample.png, it only works the first time. If I close the file and re-select it, I get an empty file. 

What is the trickery behind perhaps having a selected image show up each time it is selected? I know Yazi does this alright, and the markdown part of image.nvim works fine, but outside a markdown file, choosing a file using NeoTree as an example, I only get one nice render.

**Comment by 3rd** [comment]
It sounds like a bug in the hijack mode, could you please share your config?

**Comment by resistorsoftware** [comment]
Sure thing... 
```
return {
  {
    'vhyrro/luarocks.nvim',
    priority = 1001,
    opts = {
      rocks = { 'magick' },
    },
  },
  {
    '3rd/image.nvim',
    dependencies = { 'luarocks.nvim' },
    config = function()
      require('image').setup {
        backend = 'kitty',
        kitty_method = 'normal',
        integrations = {
          markdown = {
            enabled = true,
            clear_in_insert_mode = false,
            download_remote_images = true,
            only_render_image_at_cursor = true,
            filetypes = { 'markdown', 'vimwiki' },
          },
          neorg = {
            enabled = true,
            clear_in_insert_mode = false,
            download_remote_images = true,
            only_render_image_at_cursor = false,
            filetypes = { 'norg' },
          },
          html = {
            enabled = true,
          },
          css = {
            enabled = true,
          },
        },
        max_width = nil,
        max_height = nil,
        max_width_window_percentage = nil,
        max_height_window_percentage = 40,
        window_overlap_clear_enabled = false,
        window_overlap_clear_ft_ignore = { 'cmp_menu', 'cmp_docs', '' },
        editor_only_render_when_focused = true,
        hijack_file_patterns = { '*.png', '*.jpg', '*.jpeg', '*.gif', '*.webp', '*.avif' },
      }
    end,
  },
}

```

**Comment by Charlie-83** [comment]
I am also getting the same behaviour (I think). Works fine in markdown. If I open an image (eg foo.png) it displays perfectly, if I now do `:bn<cr>:bp<cr>` the image buffer is empty. My current solution is to use `:e` to reload the buffer and then the image is displayed again.

I have deleted everything else in my Neovim config and can still reproduce. My entire config is now:
```lua
require("lazy_setup").setup({
    {
        "3rd/image.nvim",
        dependencies = "luarocks.nvim",
        config = true,
    },
    {
        "vhyrro/luarocks.nvim",
        priority = 1000,
        opts = {
            rocks = { "magick" },
        }
    }
})
```

I am on Neovim v0.10.2

**Comment by 3rd** [comment]
Was missing the auto-command events, thank you!
