### ISSUE TITLE
Separate Buffer for images

### ISSUE THREAD

**Issue by zimzims** [3rd/image.nvim#253]
Hello,
First, thanks for a wonderful plugin. I've been using this plugin in addition to molten.nvim and quarto.nvim for my jupyter notebook experience and loving it so far! 

I was wondering if there was a way to render images in a separate buffer like the Spyder IDE does? Often when prototyping I like to run code blocks with different parameters and compare the plots later on. A scrollable buffer with images is very useful for me. 

If I'm missing a configuration option then that's wonderful. If it needs to be implemented I would love to help in whatever way I can to help build the functionality.

(If this is the wrong plugin to ask for this I'm sorry!)

Thank you,

Zimzims

**Comment by 3rd** [comment]
Hey, I think it would be better handled in a separate plugin that uses image.nvim as a library, like https://github.com/3rd/diagram.nvim
