### ISSUE TITLE
Bug: possible to render outside of NeoVim

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#28]
It's possible to render an image at the bottom of the screen that escapes into the rest of the terminal (that grey bar is the tmux bar).

![image](https://github.com/3rd/image.nvim/assets/56943754/ca609a5c-f217-4567-a70c-91123e67b659)

It would be nice for `image.nvim` to be able to automatically crop images that are going to display outside of NeoVim. It would also be amazing if there was an option to autocrop images that would display over the status bar.

**Comment by 3rd** [comment]
Was the image supposed to be bound to the window&buffer behind? I think that's the only standard "mainstream" we want to support for automatically handling things, and for other cases it should be the responsibility of the integration to do any handling it needs. I'd like to avoid checking for things like cmdheight inside the core.

I'm working on a sample plugin that renders things and is not bound to a window/buffer (on the status bar, https://github.com/3rd/image.nvim/issues/17#issuecomment-1706664350) and I'll get it out soon, been struggling with an animation.

After  I started to work on that I realized the API is not that friendly, so I have a new version coming up, that lets users call `image.crop(w, h, left, top)` and `image.resize(w, h)`, and other fixes like clearing the confusion of when a size is in term cells or pixels, etc.

**Comment by benlubas** [comment]
That image I believe was bound to a buffer but not a window. I can give a more thorough reproduction later today.

**Comment by benlubas** [comment]
Did I say later today? I meant later this week.

That issue was only when there was no window binding, so it's behaving as expected. When I bind the image to a window the image is cropped so it doesn't draw outside neovim. 

It will still draw on top of the status line, but not on top of the cmd line, regardless of `cmdheight`
