### ISSUE TITLE
Ueberzug backend is so slow that is actually unusable

### ISSUE THREAD

**Issue by Bekaboo** [3rd/image.nvim#3]
https://github.com/3rd/image.nvim/assets/76579810/89c9eef4-7094-4b33-a867-8c78728ff490

Hi, first of all, thanks for making this great plugin!

I'm excited to test it out with ueberzug backend on alacritty, but as shown in the screen recording the rendering speed is so slow that I can hardly move my cursor around and scroll the window. There's also a lot flickering.

**Comment by 3rd** [comment]
Argh, that looks bad, are you using the master version of https://github.com/jstkdng/ueberzugpp ?
Could you please share the image and your specs to reproduce it?
Is it a very large image / do you have the same issue with a 400x300 image?

Looking at this it's clear that I have to make the rendering non-blocking, thanks a lot for this insight!
I'll add a debug flag to track how much of the delay is caused by ImageMagick and how much by ueberzugpp.

**Comment by Bekaboo** [comment]
@3rd Thanks for your reply!

> Is it a very large image / do you have the same issue with a 400x300 image?

Haven't tested with smaller images, but yes, almost all the images I use in my notes have size at least 1024*1024... So I guess it is a little too big for this plugin, but that is the smallest size of images I can use if I what clear and sharp images in exported PDFs.

> Could you please share the image and your specs to reproduce it?

Sure, you can test with the following images:

![23-02-21-12-59-16](https://github.com/3rd/image.nvim/assets/76579810/5daa10cd-320d-488d-bae9-bb69300eed03)
![clustered_sparse_with_duplicate_keys drawio](https://github.com/3rd/image.nvim/assets/76579810/a7b2b5e8-19e7-4c11-898f-61e3643dea2d)

My config is pretty simple:

```lua
require('image').setup({
  backend = 'ueberzug',
  max_width_window_percentage = 80,
})
```

In addition, I'm using neovim in tmux, if that's related (not sure if it will impact the performance).

**Comment by 3rd** [comment]
@Bekaboo Thanks for the images!
Added auto-scaling now, images will be resized to the target display width/height before cropping.
It's still not perfect with ueberzugpp, but should be way better.

https://github.com/3rd/image.nvim/assets/59587503/c6aad5e5-f603-4b86-acef-58c7f469ff74

**Comment by Bekaboo** [comment]
@3rd Thanks for the quick fix, but I get this error after updating to the latest version (with exactly the same terminal and plugin config):

```lua
Error executing luv callback:
.../pack/packages/opt/image.nvim/lua/image/utils/logger.lua:45: 11:13:26 [image.nvim] im
age: ueberzug died unexpectedly {
  code = 0,
  signal = 6
}
stack traceback:
        [C]: in function 'handler'
        .../pack/packages/opt/image.nvim/lua/image/utils/logger.lua:45: in function 'thr
ow'
        .../packages/opt/image.nvim/lua/image/backends/ueberzug.lua:18: in function <...
/packages/opt/image.nvim/lua/image/backends/ueberzug.lua:15>
```

Can you reproduce the bug with **ueberzug** backend? Thanks!

**Comment by 3rd** [comment]
Hey @Bekaboo, did some improvements to separate the caching of resized images and cropped images, and it seems like it behaves better now, but I'm also able to crash Ueberzug++ by making it rerender many times in a short time span.
I'll check if a throttle would make it better, and look into debugging why it's crashing if that doesn't work out. 

https://github.com/3rd/image.nvim/assets/59587503/f326b78f-c79c-460c-8178-f68c42927f25

**Comment by Bekaboo** [comment]
@3rd Thanks for your effort! It seems much better, but after I upgrade to the latest version I get this error whenever I open a markdown file (I don't use neorg):

```
Failed to run `config` for image.nvim

.../pack/packages/opt/image.nvim/lua/image/utils/logger.lua:45: 11:43:32 [image.nvim] render: faile
to load neorg integration

# stacktrace:
  - /image.nvim/lua/image/utils/logger.lua:45 _in_ **throw**
  - /image.nvim/lua/image/init.lua:61 _in_ **setup**
  - lua/configs/image.lua:1
  - lua/modules/markup.lua:42 _in_ **config**
  - /usr/share/nvim/runtime/filetype.lua:22
  - /usr/share/nvim/runtime/filetype.lua:21
  - vim/_editor.lua:0
  - /telescope.nvim/lua/telescope/actions/set.lua:200 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **key_func**
  - /telescope.nvim/lua/telescope/mappings.lua:257
```

To make it clearer, I'll open another issue regarding to this once I find a minimal config and steps to reproduce.

**Comment by 3rd** [comment]
@Bekaboo super weird, couldn't reproduce it, but pushed an update to not wrap that error, could you please try again and provide the new stack trace?
the error should go away if you disabled the norg integration in the config, but it shouldn't error anyway, definitely a bug
