### ISSUE TITLE
Images jump around when the same buffer is open in a split and scrolled

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#30]
Kitty terminal, using kitty graphics. This is in a markdown file with 5 images rendering at the same time, but it happens with only one image as well.
maybe a mild seizure warning.

https://github.com/3rd/image.nvim/assets/56943754/3811574f-6a01-432a-a817-421f85fd1564

After trying this with only one image, it seems like it's due to the issue of extmarks belonging to a buffer, and when the buffer is scrolled, they're removed from the scrolled buffer, added back in the non-scrolled buffer, and removed and added and removed and added over and over again.

**Comment by 3rd** [comment]
Interesting effect, is the same buffer open in both windows?

**Comment by benlubas** [comment]
Yes same buffer. I just opened a file, scrolled down to load an image on screen, then `:vsplit` and scroll up in one of the splits

**Comment by 3rd** [comment]
Can you still reproduce the issue after the latest changes?

https://github.com/3rd/image.nvim/assets/59587503/35b53ee1-ef5d-4517-82cc-afd923d2da71

**Comment by benlubas** [comment]
Ooh that's great. I don't think I'll go the full script route but an alias to the ffmpeg command is for sure going in my zshrc.

**Comment by benlubas** [comment]
@3rd I can still reproduce this with the latest change

**Comment by 3rd** [comment]
@benlubas Hey, does the flicker still happen? Made some changes around extmarks that should fix that.
Unfortunately there's a tree-sitter bug as well, node:range() seems to take into account the extmark heights for some reason.

**Comment by benlubas** [comment]
@3rd I no longer have the issue when scrolling but if I open a split of the same buffer and then close the split (with images on or off screen) the bug still happens

**Comment by 3rd** [comment]
Hmm I get a bug with some extmarks not being cleared sometimes, probably a race, but I don't see any flickering. Does it still happen for you?


https://github.com/3rd/image.nvim/assets/59587503/6e710c8e-4599-4159-ab8d-3c5eb17050a0

**Comment by benlubas** [comment]
I don't see this behavior anymore
