### ISSUE TITLE
[bug] Images in floating windows with boarders

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#33]
Here is a rendered image with a window and buffer specified, and it has a position of `x=0, y=1` (with 0 indexed rows). It displays fine in a window without borders, but the window relative positioning doesn't seem to account for borders, and it just draws the image over them. 

![image](https://github.com/3rd/image.nvim/assets/56943754/2e384fe9-d58c-43e9-8eda-7a8c79231787)

I'm happy to submit a PR for this. I just want to check weather or not this is something you think `image.nvim` should handle, or if this is up to users to deal with. Personally I'd vote for respect window boarders as an on by default render option.

**Comment by 3rd** [comment]
Hey, your suggestion sounds awesome!
If we're bound to a window and it has borders I think we should account for them.
The borders can only have a width of one cell, right?

**Comment by benlubas** [comment]
Yup I see an error when trying to open borders with a width greater than 1

**Comment by benlubas** [comment]
There's a potentially related issue with moving windows around that have borders. I have an output window with a border and an image in the window, and when I scroll the screen, the window moves, and the image jumps all over the place. I haven't been able to reproduce this with a window that doesn't have borders.

After recording this video, I realized that the windows are being redrawn when scrolling (semi rapidly) so it seemed like it might be related to #34, but this happens _way_ more frequently, and only happens with bordered windows. 

lots of flashing images in this video as always.

https://github.com/3rd/image.nvim/assets/56943754/515b71a9-c84b-4638-b90d-006b170400bf

**Comment by 3rd** [comment]
Just noticed in the video that the extmarks seem to be cleared and re-created on render, will investigate.
Weird thing about the floating windows, but looks like it can help reproduce the deeper problem.
Thanks for all the effort!

**Comment by benlubas** [comment]
I can no longer reproduce this reliably
