### ISSUE TITLE
[Request] Expose `renderer.adjust_to_aspect_ratio` 

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#39]
I think this, or something similar, would make a good addition to the API. I've come across a situation where I'd like to know the rendered size of an image (accounting for user settings) before I actually render it.

Given that all the information this function needs is exposed to the user in some way or another before render is called, I could just duplicate this logic in my own plugin. But then if this logic changes (which it may, given that it currently squishes images to align to the terminal grid) then I (and potentially others) would need to change things.

This change could be as simple as adding the function to the return statement in `renderer.lua`, or we could potentially make a nicer function on image itself that calculates the same information, such as `img:rendered_size()` without needing to take a bunch of arguments.

Thoughts?

**Comment by 3rd** [comment]
:fire: Good idea to expose those, I moved them into utils in https://github.com/3rd/image.nvim/commit/d7e9845b14e4fbdd0136e33d59b5b2b7d5414bef

```lua
local utils = require("image/utils");

utils.offsets.get_global_offsets(window.id)
utils.math.adjust_to_aspect_ratio(term_size, image.image_width, image.image_height, width, height)
```

Something like `img:get_simulated_rendered_size()` would be complicated to do now (should rework `image.rendered_geometry` as well), but it's something to consider at the next refactor.

Working on a good API for the plugin, right now it's a messy first implementation, but it will get better soon!
