### ISSUE TITLE
Add to luarocks

### ISSUE THREAD

**Issue by NTBBloodbath** [3rd/image.nvim#4]
Hey, I think you could add your nice plugin to luarocks so we can just `luarocks install` it alongside to its dependencies. You can use this [awesome tool](https://github.com/nvim-neorocks/luarocks-tag-release) to automate _almost_ the whole process for you (even creating the rockspec file iirc) :)

Cheers!

**Comment by 3rd** [comment]
Hey, yes, definitely on my list!
Followed the discussion here https://github.com/folke/lazy.nvim/issues/253 and thought a bit about how to fix the "install it yourself" part, but parked it for a while until I figure out how to get the `magick` rock to work without monkey patching on NixOS.
Will for sure pack and publish it to luarocks, thanks you!

**Comment by vhyrro** [comment]
I actually spent a little creating a writeup on how to automate the process of publishing a Neovim plugin to luarocks, maybe it could be of some use to get things up and running quickly? :D

https://github.com/vhyrro/sample-luarocks-plugin

**Comment by 3rd** [comment]
I put it off mainly because I didn't have time to look into how to get started, thanks for doing all that work, I'll follow your guide and get it published tomorrow <3

**Comment by 3rd** [comment]
:tada: Thanks for all the help! https://luarocks.org/modules/3rd/image.nvim
