### ISSUE TITLE
Inconsistent Cropping Behavior

### ISSUE THREAD

**Issue by 3rd** [3rd/image.nvim#42]
### Discussed in https://github.com/3rd/image.nvim/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **benlubas** October  9, 2023</sup>
I just have a question about the way cropping works when an image is too big to fit where it's placed.

I feel like I've seen two behaviors:
1. The image gets cropped and you only see part of it, but it's aspect ratio stays the same, but part of it is missing
2. the image gets shrunk, and you can still see the entire thing, but it get's smaller and smaller

number two is the behavior that I've seen more recently, and I'm wondering what has changed, is that a kitty thing? or something that the plugin is doing? I see that the kitty backend in this plugin has the "crop" feature, so I'm guessing that this is something kitty is doing, and the other behavior was the way image magick was cropping images.

I do prefer behavior 1, where it just shows part of the image and I have to scroll to see the rest. Is there currently a way to configure the plugin to use that behavior with kitty?

</div>

**Comment by jmbuhr** [comment]
In a more isolated setting, only rendering the image at the cursor, what I see is that when I first jump to a line, e.g. using a search or a mark, it crops and shows the top left corner (behaviour 1):

![image](https://github.com/3rd/image.nvim/assets/17450586/b786f470-f426-47b6-a7ee-0a4629ac4e1d)

but after moving from and back to the line once (`jk`) it shows the scaled image:

![image](https://github.com/3rd/image.nvim/assets/17450586/8927b6bd-683f-48a8-b051-8b28025d91bc)

then, after scrolling with the mouse wheel and clicking back to the line I get and even smaller version:

![image](https://github.com/3rd/image.nvim/assets/17450586/affd2523-8477-47e5-8c7a-799843b294bf)

**Comment by benlubas** [comment]
I'm here to add that opening a large enough floating window allows the image to render without being cropped, but it's scaled to half the size that it should be. I see this behavior in Molten as well

![image](https://github.com/3rd/image.nvim/assets/56943754/2b89fba2-091d-48b0-8154-96a96e6a0638)

**Comment by benlubas** [comment]
I found some code in renderer that assumes width and height are equal values when dealing with cell width and height. 

Easy mistake to make, took me literally staring it in the face to notice. I'd say I'll have a PR up shortly, but I feel like I'm looking at more than one bug here, so we'll see

**Comment by jmbuhr** [comment]
@3rd PS: This plugin is super exciting, you are a wizard! I can't stop smiling about the penguins with transparent background right in my quarto document!

**Comment by benlubas** [comment]
Now to deal with this: Images getting both scaled and cropped, when one or the other would do

https://github.com/3rd/image.nvim/assets/56943754/d0fdbc12-dba3-4009-9adb-2359a867fb3b

**Comment by benlubas** [comment]
@jmbuhr  I think #46  also fixes the issue you described. I don't seem to be having it anymore

**Comment by benlubas** [comment]
Okay, there's actually still one inconsistency here. 

https://github.com/3rd/image.nvim/assets/56943754/bb2b2c6b-d94c-43ed-8522-ded04e8b2815

**Comment by 3rd** [comment]
We can add a image.auto_resize bool to turn off resizing per-image, would that work?

**Comment by benlubas** [comment]
My issue is more with when it resizes and when it doesn't, it's currently not consistent between images that have a window and images that don't have a window. So if we add auto-resize could we make it off by default?

**Comment by 3rd** [comment]
Not sure if left/right crop is implemented with Kitty, will check.
If an image is not mounted on a window & buffer it shouldn't be resized/cropped at all, the API user should have full control.
For images that are attached to a window and buffer it should behave the same and crop images at the window bounds, images should not be resized depending on scroll position.
I'll look into it!

**Comment by benlubas** [comment]
I have a branch that makes things so they work the way you just described and adds left/right crop

@3rd

**Comment by benlubas** [comment]
https://github.com/3rd/image.nvim/assets/56943754/c3423539-4a52-46a8-bcd3-66b3d2137f69
