### ISSUE TITLE
[perf] cache images for `only_render_image_at_cursor` and/or run async

### ISSUE THREAD

**Issue by jmbuhr** [3rd/image.nvim#55]
When having fairly large images (e.g. different sizes of https://www.pexels.com/photo/scenic-view-of-mountains-during-dawn-1261728/) in a markdown document, nvim blocks when the cursor reaches the image line to process the image.

This could be improved by running the processing async such that one could still scroll over the image and by caching the result such that the processing doesn't have to happen again when the cursor reaches the line a second time.

https://github.com/stevearc/profile.nvim
![image](https://github.com/3rd/image.nvim/assets/17450586/ee733ba6-2633-4cb2-af9b-7ed50986d352)

**Comment by 3rd** [comment]
Yep, all that should be lazy, been on the list for a while.
How did you get that profiler to work? It never worked for me.

![image](https://github.com/3rd/image.nvim/assets/59587503/05980c01-2924-4070-b525-3ab9a1dbcfab)

**Comment by jmbuhr** [comment]
I also have an issue with the latest commits, but the `9857b90ad5b66ef17b3e134eb485f49b6a62a3c8` works for me

**Comment by 3rd** [comment]
Wasn't able to get the profiler running :(
Added caching in https://github.com/3rd/image.nvim/commit/e9fd31074c9cfd4ca2759313c560247fe5dada1d
ImageMagick takes a lot of time with the :write(), not sure why it would be so bad, maybe there's an easy fix.
Tried to make the image rendering async for documents, but it would still block for some reason.
Maybe I didn't do it right, tried something like this:

```lua
local co = coroutine.create(function(cb)
  local ok, image = pcall(ctx.api.from_file, path, {
    id = item.id,
    window = item.window.id,
    buffer = item.window.buffer,
    with_virtual_padding = true,
  })
   cb(ok, image)
end)

vim.uv.new_async(function()
  coroutine.resume(co, function(ok, image)
    vim.schedule(function()
       if ok then render_image(image) end
    end)
  end)
end):send()
```
