### ISSUE TITLE
[FEATURE] Visualize image files inside the buffer.

### ISSUE THREAD

**Issue by pysan3** [3rd/image.nvim#56]
Hi, introduced by the neorg community, I'm having a wonderful time with your plugin!

I was wondering if this plugin could be extended to visualizing `png`, `jpg` etc images.
When opening images inside neovim, currently it just displays binary junk but it would be awesome if this plugin could hijack the buffer and display the actual image.

I found this plugin: https://github.com/samodostal/image.nvim which uses ascii chars to do something similar. 

I would love to hear your opinion. Thanks in advance.

**Comment by 3rd** [comment]
Hey, thanks for the kind words, we should be able to do something like that easily!

**Comment by 3rd** [comment]
:man_dancing: :woman_dancing: :man_dancing: :woman_dancing: :man_dancing: :woman_dancing: 

https://github.com/3rd/image.nvim/assets/59587503/57e7489b-65ac-44f9-911c-2f63123326b9

**Comment by pysan3** [comment]
OMG, what a quick move!

Thank you very much @3rd <3

**Comment by pysan3** [comment]
Working on integrating it to neo-tree ;)

https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1196

**Comment by 3rd** [comment]
Uu nice, neo-tree looks great. Been thinking of trying it, last time I got a bit overloaded by all the options it has <3

**Comment by pysan3** [comment]
> I got a bit overloaded by all the options it has 

True lol. Well we had a quite big refactoring about a month ago and it might have gotten better. 

And some neovim distros uses neo-tree and hosts their own config so they might be a good reference. What come to my mind are [LazyVim](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/editor.lua#L7) and [AstroNvim](https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/neo-tree.lua).

**Comment by vhyrro** [comment]
I can't lie this is a super dope feature, thanks for introducing it :D
