### ISSUE TITLE
Geometry not respected

### ISSUE THREAD

**Issue by Poly2it** [3rd/image.nvim#57]
I cannot get image.nvim to respect options for width and height in image geometry. All attempts result in the image shrinking to a single character unit in width and height. I would expect it to snap to the closest multiple of the character unit (although it would be nice if more snapping options were available, like only snapping on one axis).

```lua
...

local geometry = { x = 0, y = 0, width = 1000, height = 1000 } -- no size works
local symbol = image.from_file("/home/user/image.png", {})
symbol:render(geometry)
```

**Comment by 3rd** [comment]
Interesting, could be a bug when both are provided, or something else. Will check!
The width/height should be in term cells, not pixels.

![image](https://github.com/3rd/image.nvim/assets/59587503/6305b4e8-cf06-4f72-ba6f-127f9150b577)

![image](https://github.com/3rd/image.nvim/assets/59587503/cd7e2538-4661-4a1a-a04c-ca39a2d06735)

**Comment by 3rd** [comment]
It won't scale the image up if it's smaller than the target size. Could you share the image?

**Comment by Poly2it** [comment]
> Interesting, could be a bug when both are provided, or something else. Will check!
> The width/height should be in term cells, not pixels.
Hm, I tried only setting one parameter initially, but it did not have any effect either.

> It won't scale the image up if it's smaller than the target size. Could you share the image?

It's a 64x64 render of a mimetype icon from https://github.com/somepaulo/MoreWaita. 
![test](https://github.com/3rd/image.nvim/assets/84731064/8b188c64-19c4-4a9b-8113-e6e3b1565980)

**Comment by Poly2it** [comment]
An update: interestingly it seems to work on my machine now. I went for lunch without changing anything, now the image is displaying with respect to the width attribute.

**Comment by 3rd** [comment]
Ah damn, my least favourite kind of bug :(

**Comment by 3rd** [comment]
I'll close this for now, let's reopen it if it comes back :man_dancing: :woman_dancing:
