### ISSUE TITLE
Image not cleared after switching tmux window

### ISSUE THREAD

**Issue by Bekaboo** [3rd/image.nvim#63]
After some exploration I found another issue that after switching tmux window the image in the previous window is not cleared.

Here is a short screen recording that demonstrate it:

https://github.com/3rd/image.nvim/assets/76579810/37747843-f61c-4e9a-a367-c53631793f58

Environment:

- Terminal: `kitty 0.29.2` + `tmux 3.3a` (with `allow-passthrough` on)
- Neovim: `NVIM v0.10.0-dev-1334+gd2d38858d1`
- image.nvim: `1cb60be1cdc108e3a3b09cb0ed115ef75ce51320`
- OS: `Linux 6.1.58-1-lts `

Plugin config:

```lua
package.path = table.concat(
  {
    package.path,
    vim.fs.normalize('~/.luarocks/share/lua/5.1/?/init.lua'),
    vim.fs.normalize('~/.luarocks/share/lua/5.1/?.lua'),
  },
  ';'
)

require('image').setup({
  window_overlap_clear_enabled = true
})
```

**Comment by Bekaboo** [comment]
Also the `window_overlap_clear_enabled` option does not seem to work:

![image](https://github.com/3rd/image.nvim/assets/76579810/95e81087-125a-4cb9-99e7-04d04b94f401)

**Comment by 3rd** [comment]
Hey, you need to set `tmux_show_only_in_active_window = true` and also `set -g visual-activity off` in your Tmux config.
It's all a big hack, it will try to find the tty you switched to and write the clearing control sequence to it :eyes:

**Comment by Bekaboo** [comment]
It works, thanks for quick response!

**Comment by Bekaboo** [comment]
@3rd The `window_overlap_clear_enabled` still does not work, though:

![image](https://github.com/3rd/image.nvim/assets/76579810/47b9c582-1951-4bc4-ab24-08bf08c512aa)

After `:call nvim_open_win(nvim_create_buf(0, 0), 0, { 'col':10, 'row':8, 'width':100, 'height':20, 'relative':'editor' })` (open a floating window that covers the image):

![image](https://github.com/3rd/image.nvim/assets/76579810/ef40a0aa-c26a-4fa2-b292-9f98e72bcd8b)

**Comment by 3rd** [comment]
It's because the buffer has no filetype and of the `window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" }` default.

**Comment by Bekaboo** [comment]
Thanks, setting this option to empty table solves the problem.

**Comment by Bekaboo** [comment]
Thanks, setting this option to empty table solves the problem.
