### ISSUE TITLE
[Bug] Splitting tmux window makes images mis-positioned

### ISSUE THREAD

**Issue by Bekaboo** [3rd/image.nvim#64]
Environment:

- Terminal: `kitty 0.29.2` + `tmux 3.3a` (with allow-passthrough on)
- Neovim: `NVIM v0.10.0-dev-1334+gd2d38858d1`
- image.nvim: `1cb60be1cdc108e3a3b09cb0ed115ef75ce51320`
- OS: `Linux 6.1.58-1-lts` 

Minimal plugin config:

```lua
require('image').setup({
  backend = 'kitty',
  window_overlap_clear_enabled = true,
  tmux_show_only_in_active_window = true,
})
```

Steps to reproduce:

1. Open kitty terminal
2. Execute `tmux`
3. Using nvim with image.nvim installed and configured to open a markdown file with contents

    ```markdown
    ![ConvExample](https://stanford.edu/~shervine/teaching/cs-230/illustrations/convolution-layer-a.png?1c517e00cb8d709baf32fc3d39ebae67)

    For a convolutional operation, the stride 
    **S** denotes the number of pixels by which the window moves after each operation.
    ![StrideExample](https://stanford.edu/~shervine/teaching/cs-230/illustrations/stride.png?36b5b2e02f7e02c3c4075a9d836c048c)
    ```
4. Split current tmux window horizontally or vertically
5. Images get misplaced

Screenshots:

- Before splitting:

    ![Screenshot_20231024_154533](https://github.com/3rd/image.nvim/assets/76579810/c4f407af-2258-442e-904b-208ddd870ca4)

- After splitting (first image goes to the new tmux pane at bottom, second image disappears):

    ![Screenshot_20231024_154552](https://github.com/3rd/image.nvim/assets/76579810/a1d928a7-dbc3-4d65-8a56-0bc11b5563a3)

**Comment by 3rd** [comment]
:heavy_check_mark:  wawaweewa
It's still gonna be weird if you resize the Neovim pane while a different one holds the focus, but works great if you don't do that.

https://github.com/3rd/image.nvim/assets/59587503/0a5d5e46-0a27-4e63-8b46-da1aca0acd5a

**Comment by Bekaboo** [comment]
Works great, thanks!
