### ISSUE TITLE
[Bug] `magick.load_image()` returns nil

### ISSUE THREAD

**Issue by Bekaboo** [3rd/image.nvim#65]
The call to `magick.load_image()` in `lua/image/image.lua` at line 265 can return `nil` which  causes error at line 268 every time the text being changed inside current buffer:

https://github.com/3rd/image.nvim/blob/6598813b4c4e395eba0b2217cd6458aaa58b897f/lua/image/image.lua#L265

https://github.com/3rd/image.nvim/assets/76579810/bdb2a1c8-1b5b-4215-a471-bfe1203911cf

**Comment by 3rd** [comment]
Thanks for the issue, should be ok now!

**Comment by Bekaboo** [comment]
It works greate, thx! :heart:
