### ISSUE TITLE
adding text above images that are out of view duplicates those images

### ISSUE THREAD

**Issue by jmbuhr** [3rd/image.nvim#67]
If I take the minimal example and add a bunch of lines above the line that shows the image until said line is out of view and then scroll down I end up with this:

![image](https://github.com/3rd/image.nvim/assets/17450586/6363d959-ce70-49e2-be75-8dead0a16d5b)

**Comment by jmbuhr** [comment]
I can see the image being rendered multiple times in the profile by adding the nvim.profile plugin to the minimal example:
https://gist.github.com/jmbuhr/3b7102708f8fe565ed0d0fd69c2de746

**Comment by jmbuhr** [comment]
They use the same cropped_path, but have different ids 
![image](https://github.com/3rd/image.nvim/assets/17450586/93b07675-3be4-4f1f-856f-dbb9c61b4621)

**Comment by 3rd** [comment]
Thanks for the issue! It's fixed now.
It was because clearing was limited to rendered images :man_facepalming:

**Comment by jmbuhr** [comment]
Found another one of those bugs :bug:, but it is a bit weird to reproduce.
If I open nvim in a directory and then edit an image-enabled file in a subdirectory, adding lines above the image does not move it.

`nvim` followed by `:e subdir/test.qmd`

![image](https://github.com/3rd/image.nvim/assets/17450586/fe722135-6258-4f08-8ea0-2e4a7c370781)

And deleting lines above an image leads to a ghost image:

![image](https://github.com/3rd/image.nvim/assets/17450586/6029632d-0e41-4558-83ac-0cd9bc8c8d6b)


but `nvim subdir/test.qmd` works fine:

![image](https://github.com/3rd/image.nvim/assets/17450586/822123c7-35d6-423d-b468-dff3df6bdffd)
