### ISSUE TITLE
Updating of images is sporadic

### ISSUE THREAD

**Issue by shblythe** [3rd/image.nvim#70]
If I add an image link in a markdown file, often the image doesn't appear until I load another file, and then go back to the original file.
The same happens when I delete an image link (the image doesn't disappear), but not if it's the last image link I added to the file.
(Version c91d47c)

**Comment by shblythe** [comment]
Here's my config:
`                backend = "kitty",
                integrations = {
                    markdown = {
                        enabled = true,
                        clear_in_insert_mode = false,
                        download_remote_images = true,
                        only_render_image_at_cursor = false,
                        filetypes = { "markdown", "vimwiki" },
                    },
                },
                max_width = nil,
                max_height = nil,
                max_width_window_percentage = nil,
                max_height_window_percentage = 50,
                window_overlap_clear_enabled = true, -- toggles image when windows are overlapped
                window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
                editor_only_render_when_focused = false,
                tmux_show_only_in_active_windows = false,
                hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp" },
`

I've also checked and confirmed that it still occurs if window_overlap_clear_enabled is false.

**Comment by 3rd** [comment]
Hey, thanks for the issue!
I wasn't able to reproduce it, can you create a minimal scenario?
Does it go "back to normal" if you scroll up/down?

**Comment by shblythe** [comment]
Hi, I can't repro it on my home PC for some reason, which might turn out to be useful information.
I'll try again at work tomorrow and report back.

**Comment by shblythe** [comment]
Interesting, I can no longer repro it on my work PC either! :smiling_face_with_tear: 

Sorry to waste a bit of your time!  I'll continue to monitor and see if it reoccurs.

**Comment by 3rd** [comment]
No worries! Please reopen if you find anything weird <3
