### ISSUE TITLE
Is it normal for images to dissappear from the buffer when kitty resizes?

### ISSUE THREAD

**Issue by TheM1Stery** [3rd/image.nvim#75]
I'm using a tiling wm. So, for example when i open a new app and kitty resizes, the images in the buffer just dissappear. In place of them is just blank space. Is there a way of fixing this issue? Thanks!

**Comment by 3rd** [comment]
I think we hit the same issue as nnn here: https://github.com/jarun/nnn/issues/1050
It seems that when Kitty is resized it looses the transmitted images, the fix/workaround is to dump the index and force-rerender all the images.
Thanks for reporting the issue!
