### ISSUE TITLE
Wezterm iterm2 support 

### ISSUE THREAD

**Issue by constantitus** [3rd/image.nvim#86]
Is wezterm support over the iterm2 protocol possible ?
Wezterm does have support for the kitty image protocol, but it's not working all that well.

https://github.com/3rd/image.nvim/assets/118078873/df961ba2-8a82-437f-8230-4500083fecf5

**Comment by 3rd** [comment]
There's no iterm2 support.

**Comment by constantitus** [comment]
> There's no iterm2 support.

I know that. I'm asking if there are any plans to implement it. Otherwise I'm gonna have to wait for wezterm to fix the support for the kitty protocol, which is unlikely to happen too soon.

**Comment by 3rd** [comment]
Salut! No plans for iterm2, got other reports on Wezterm working great with the plugin, but there's not much to do.
I'm don't know what it would take to implement it, but I wouldn't maintain a graphics protocol targeted at a Mac app.
We will have a sixel backend in the future though! https://github.com/3rd/image.nvim/issues/59
