### ISSUE TITLE
Scrolling becomes noticably slower in recent versions

### ISSUE THREAD

**Issue by Bekaboo** [3rd/image.nvim#89]
Thanks for making image.nvim, it is awesome. I just updated the plugin and noticed that it has become much slower than before:

Scrolling with image.nvim using commit 1650eccca5b0d071d1305c17646ad16693987796:

https://github.com/3rd/image.nvim/assets/76579810/e0063b57-dc27-4db5-83ea-d1a217b9b6fe

Scrolling with image.nvim using commit 0ed70e2:

https://github.com/3rd/image.nvim/assets/76579810/106da79b-7153-42a0-811d-d7782e1cf0b3

Plugin config:

```lua
package.path = table.concat({
  package.path,
  vim.fs.normalize('~/.luarocks/share/lua/5.1/?/init.lua'),
  vim.fs.normalize('~/.luarocks/share/lua/5.1/?.lua'),
}, ';')

require('image').setup({
  backend = 'kitty',
  window_overlap_clear_enabled = true,
  tmux_show_only_in_active_window = true,
  window_overlap_clear_ft_ignore = {},
  max_width_window_percentage = 80,
  max_height_window_percentage = 30,
})
```

Neovim version:

```
NVIM v0.10.0-dev-1627+g879617c9bb
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

OS: `Arch linux Linux 6.1.63-1-lts`

Terminal: `kitty 0.31.0` + `tmux 3.3a`

**Comment by 3rd** [comment]
fixed in https://github.com/3rd/image.nvim/commit/2aad3ad35e136240a7b2fb53a50d87358f867463
