### ISSUE TITLE
Issues with neovide

### ISSUE THREAD

**Issue by serhez** [3rd/image.nvim#90]
When attempting to use the plugin with neovide, I get `.../image.nvim/lua/image/utils/term.lua:34: Failed to get terminal size`. Is the plugin supposed to work in neovide in some way or there is no support for it?

Thanks!

**Comment by 3rd** [comment]
There's no support to Neovide, it's meant for terminal emulators, mainly for Kitty.

**Comment by linkarzu** [comment]
@serhez  you can disable image.nvim in Neovide to avoid that error when you open it, I do that in the disabled.lua file. I use the lazyvim.org distro
- I have a [video for this](https://youtu.be/rNYtfA4zlO4)

<div align="left">
    <a href="https://youtu.be/rNYtfA4zlO4">
        <img
          src="https://github.com/user-attachments/assets/9cc5a0f1-632d-44c0-92d1-3952cdc36de7"
          alt="My complete Neovim markdown setup and workflow in 2024"
          width="400"
        />
    </a>
</div>

**Comment by serhez** [comment]
Thank you both for the info @linkarzu @3rd! I appreciate the replies.
