### ISSUE TITLE
No image, just a placeholder (foot terminal, ueberzug)

### ISSUE THREAD

**Issue by vacuumbeef** [3rd/image.nvim#94]
Hello, i'm trying to use it with vimwiki on my arch linux.
So, foot terminal with ueberzug backend, I have the same issue mentioned here https://github.com/3rd/image.nvim/issues/12
I use ueberzugpp in vifm to display images, so it works, but here, using the `minimal-setup.lua` I get nothing (I'm not saying about my own config, as it does not work at all yet)
![scrpart-2023-12-05-17-18-44](https://github.com/3rd/image.nvim/assets/51813411/4fff79d2-9f5e-4247-8f88-2018ace23c09)

For me it works only in kitty with kitty backend. Help me please, I want to use this thing so much

**Comment by 3rd** [comment]
AFAIK ueberzugpp work on wayland with sixels, and that's not supported now.

Sixel issue: https://github.com/3rd/image.nvim/issues/59

The ueberzug part of this plugin only works with X.Org, and direct sixel support is on the roadmap but not a priority (for me, at least until I can take a 2 week break to migrate my setup to wayland and find workarounds for all the ways it's going to break my workflow :joy:)

ueberzugpp on X.Org:
https://github.com/3rd/image.nvim/assets/59587503/c5845bd1-a0cc-41a4-8e6c-82632e56879c
