### ISSUE TITLE
[Feature] Support for other terminal emulators such as iTerm2

### ISSUE THREAD

**Issue by daiki0381** [3rd/image.nvim#97]
Hi. Thank you for your wonderful plugin.

I usually use iTerm2 as my terminal emulator, and I'm wondering if it's possible to render images at specified positions within the buffer in iTerm2.

It seems that iTerm2 also has a protocol for displaying images.

https://iterm2.com/documentation-images.html

**Comment by 3rd** [comment]
Could add after sixels https://github.com/3rd/image.nvim/issues/59, on Linux which terminal emulator implements it the best?

**Comment by daiki0381** [comment]
@3rd 

Thanks for your reply.

I commented on #59.

https://github.com/3rd/image.nvim/issues/59#issuecomment-1857312577
